### ISSUE TITLE
Pages for frontend

### ISSUE THREAD

**Issue by adrianmcli** [studydefi/dedge#2]
The pages we will need:

- [ ] Connect your MetaMask
- [ ] Import your MakerDAO Vault into our Smart Wallet
- [ ] List of imported Vaults
- [ ] Transfer Vault to Compound
- [ ] Swap debt on Compound on the user's behalf

@kendricktan does this look correct? Feel free to edit this comment directly.

**Comment by kendricktan** [comment]
Looks good

**Comment by adrianmcli** [comment]
nts: steps left to do for `compound.js`:

- [ ] supply 2 ETH and borrow 95 DAI
- [ ] swap collateral from ETH to USDC
- [ ] swap debt from DAI to BAT
- [ ] swap debt from BAT to ZRX
- [ ] swap debt from ZRX to ETH
- [ ] swap debt from ETH to DAI

**Comment by kendricktan** [comment]
You can make those into a dropdown box so its more generic.
i.e. user can select if they want to swap their supply/borrow, and the old and new tokens.

We also have a new functionality called "clear dust" which just clears the dust (borrow/supply) from the old token to the new token
