### ISSUE TITLE
Dashboard Add 2 Buttons

### ISSUE THREAD

**Issue by kendricktan** [studydefi/dedge#21]
In your `Collateral` / `Debt` table (i.e. the main dashboard)
It would be great to have 2 buttons on each row to allow the users to supply/borrow/payback/withdraw

If its a borrowed token (debt):
    - Borrow, and Payback
If its a collateral:
    - Supply and withdraw

The issue with the `supply` functionality is that the frontend needs to check if the user has allocated an allowance for the proxy (so the proxy can do `transferFrom`). If the user has not allocated an allowance, you will need a 'approve' button to allocate the allowance for the proxy, so the proxy can access the user's erc20 funds. __There is no way around this__ as it relies on msg.sender to allocate the funds.

This would be the final feature otherwise people might be too scared to use it in case they can't withdraw their funds out.

**Comment by adrianmcli** [comment]
This is done, I believe. Although we should probably indicate this better:

- Borrow and Payback is for Debt
- Supply and Withdraw is for Collateral
